[package]
name = "ssr_template_benchmarks"
version = "0.1.0"
edition = "2021"

[dependencies]
hyped = { path = "/Users/sean/Developer/swlkr/hyped" }
divan = "0.1.8"
maud = { version = "0.25.0" }

[[bench]]
name = "hyped"
harness = false

[[bench]]
name = "maud"
harness = false
